spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gulimall-ums

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-member


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto


server:
  port: 8000


seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}_tx_group
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT
  client:
    rm:
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
      default-global-transaction-timeout: 600000
      degrade-check: false
      degrade-check-period: 2000
      degrade-check-allow-times: 10
  service:
    disable-global-transaction: false
  config:
    type: nacos
    nacos:
      namespace: 46496c29-72e4-4a83-9426-d898d133373b
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      namespace: public
      server-addr: 127.0.0.1:8848
      cluster: default
      username: nacos
      password: nacos
  log:
    exception-rate: 100