server:
  port: 30000
spring:
  cloud:
    alicloud:
      access-key: LTAI5tNQ9u58Jh4RWv2Menk9
      secret-key: n7DaMqLlGdb72SrhnG9QJrvFRhLsIO
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall-xwh
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party

